/**
 * HTML doc wrapper.
 *
 * The provider takes a full HTML document (not a fragment). This module
 * wraps a body fragment in a printable document with:
 *   - the @page rules from `app/print.css` (so margin / page size
 *     stay in sync with the on-screen preview — the same source is
 *     what the browser loads for Ctrl+P)
 *   - inlined CSS (the compiled Tailwind + any custom rules)
 *   - the basics meta tags (charset, viewport, no-cache)
 *
 * The compiled CSS lives at `lib/pdf-render/print.css` and is generated
 * by `pnpm pdf:css:build` (Tailwind v4 CLI). It's committed so a fresh
 * clone works without needing a build step. If you edit `app/print.css`,
 * re-run the build to regenerate this file before committing.
 *
 * The `wrapHtml()` seam still accepts a `cssText` override so callers
 * can pass per-template CSS (Phase 2.3 — different template accents,
 * template-specific rules) without going through the global file.
 */

import 'server-only';

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { RenderOptions } from './types';

/**
 * Default @page + body CSS. Used when the compiled `print.css` is
 * missing (developer forgot to run `pnpm pdf:css:build`) AND a caller
 * doesn't pass an explicit `cssText`. Keeps the renderer from crashing
 * in that case — the output is unstyled but functional.
 *
 * Declared above `loadCompiledCss` so the catch branch (which references
 * it) doesn't trip a TDZ ReferenceError when `print.css` is missing.
 */
export const DEFAULT_PRINT_CSS = `
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 11pt; line-height: 1.4; }
  h1, h2, h3, h4 { margin: 0; }
  h1 { font-size: 20pt; font-weight: 700; }
  h2 { font-size: 13pt; font-weight: 600; margin-top: 12pt; }
  h3 { font-size: 11pt; font-weight: 600; }
  p { margin: 0 0 6pt; }
  ul { margin: 0 0 6pt 18pt; padding: 0; }
  .page-break-before { break-before: page; }
  .page-break-after { break-after: page; }
  .avoid-break { break-inside: avoid; }
`;

/**
 * Load the compiled print CSS at module init. The file is generated by
 * `pnpm pdf:css:build` from `app/print.css`. If the file is missing
 * (someone forgot to run the build), we fall back to DEFAULT_PRINT_CSS
 * and warn loudly so the problem surfaces in dev — not in a "why does
 * the PDF look unstyled" production ticket.
 */
function loadCompiledCss(): string {
  try {
    // Relative to this file: lib/pdf-render/ → ./print.css
    const path = join(__dirname, 'print.css');
    return readFileSync(path, 'utf8');
  } catch (err) {
    console.warn(
      '[pdf-render] lib/pdf-render/print.css is missing. ' +
        'Run `pnpm pdf:css:build` to compile it from app/print.css. ' +
        'Falling back to DEFAULT_PRINT_CSS for this render.'
    );
    return DEFAULT_PRINT_CSS;
  }
}

/** Module-level cache. Read once, reuse for every render. */
const COMPILED_PRINT_CSS: string = loadCompiledCss();

/**
 * Wrap an HTML body fragment in a full document suitable for the PDF API.
 *
 * @param body  - the rendered template HTML (already-rendered React output)
 * @param cssText - optional CSS override. Defaults to the compiled
 *                  `lib/pdf-render/print.css` (the Tailwind output from
 *                  `app/print.css`). Pass a custom string for per-template
 *                  accents or template-specific rules (Phase 2.3).
 * @param options - render options; the page size and margins land in @page
 */
export function wrapHtml(
  body: string,
  cssText: string = COMPILED_PRINT_CSS,
  options: Required<RenderOptions>
): string {
  // Note: we keep this template literal tight to avoid accidentally
  // injecting user-controlled content into the doc head. The only
  // interpolated values are cssText (caller-controlled, no user data)
  // and body (caller-controlled, but escaped by React before it gets
  // here).
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Resume</title>
<style>
  /* Page setup — mirrors app/print.css. Kept in sync by convention. */
  @page { size: ${options.format === 'a4' ? 'A4' : 'letter'}; margin: ${options.marginMm}mm; }
  @media print {
    html, body { margin: 0; padding: 0; }
  }
  html, body { background: #fff; color: #111; }
  ${cssText}
</style>
</head>
<body>
${body}
</body>
</html>`;
}
