import Image from 'next/image';

/**
 * Nexstepper brand marks (added 2026-10-09).
 *
 * Source art lives in `public/brand/`, generated by
 * `scripts/process-brand.ps1` from the master files in Downloads.
 * The script auto-crops the transparent padding and resizes to
 * web-appropriate dimensions — the originals were 2560×1440 / 2048×2048
 * PNGs totalling 4.6 MB, which is far too heavy for a 28px header mark.
 *
 * | variant      | use                                        |
 * |--------------|--------------------------------------------|
 * | `horizontal` | wordmark + tagline — nav bars, footers       |
 * | `stacked`    | square-ish lockup — about / hero / OG       |
 * | `icon`       | mark only — favicon, tight spaces           |
 *
 * ## Dark mode
 *
 * The artwork is a single dark-navy colour on transparency, which is
 * invisible against this app's dark background. Because it is
 * monochrome, `invert()` produces an exact light version rather than
 * an approximation — hence `dark:invert` on every render.
 */
const LOGOS = {
  horizontal: {
    src: '/brand/nexstepper-horizontal-clean.png',
    width: 640,
    height: 141,
    alt: 'Nexstepper'
  },
  stacked: {
    src: '/brand/nexstepper-stacked-clean.png',
    width: 420,
    height: 331,
    alt: 'Nexstepper'
  },
  icon: {
    src: '/brand/nexstepper-icon-clean.png',
    width: 256,
    height: 274,
    alt: ''
  }
} as const;

export type LogoVariant = keyof typeof LOGOS;

export function Logo({
  variant = 'horizontal',
  height = 28,
  priority = false,
  className
}: {
  variant?: LogoVariant;
  /** Rendered height in px; width is derived from the aspect ratio. */
  height?: number;
  priority?: boolean;
  className?: string;
}) {
  const logo = LOGOS[variant];
  const width = Math.round((logo.width / logo.height) * height);

  return (
    <Image
      src={logo.src}
      alt={logo.alt}
      width={width}
      height={height}
      priority={priority}
      style={{ height: `${height}px`, width: `${width}px` }}
      className={[
        'shrink-0 object-contain dark:invert',
        className ?? ''
      ]
        .filter(Boolean)
        .join(' ')}
    />
  );
}